module.exports = [
  "unrest, conflicts and war",
  "act of terror",
  "armed conflict",
  "revolutions",
  "rebellions",
  "religious conflict",
  "social conflict",
  "guerilla activity",
  "bioterrorism",
  "bombings",
  "massacre",
  "genocide",
  "riots",
  "war",
  "civil war",
  "prisoners and detainees",
  "conflict (general)",
  "weaponry",
  "national security",
  "armed Forces",
  "military equipment",
  "firearms",
  "biological and chemical weapons",
  "missile systems",
  "nuclear weapons",
  "suicide"
];